-- AlterTable: Add Form 9 specific fields to submissions
ALTER TABLE "submissions"
ADD COLUMN "f9PropertyOwnerType"   TEXT,
ADD COLUMN "f9PropertyOwnerName"   TEXT,
ADD COLUMN "f9NIC"                 TEXT,
ADD COLUMN "f9BusinessRegNo"       TEXT,
ADD COLUMN "f9VATRegNo"            TEXT,
ADD COLUMN "f9OwnerContactNo"      TEXT,
ADD COLUMN "f9PremisesAssNo"       TEXT,
ADD COLUMN "f9PropertyType"        TEXT,
ADD COLUMN "f9ConsiderationRs"     TEXT,
ADD COLUMN "f9PlanNo"              TEXT,
ADD COLUMN "f9LotNo"               TEXT,
ADD COLUMN "f9Facilities"          TEXT,
ADD COLUMN "f9COCDate"             TEXT,
ADD COLUMN "f9GMCApprovalNo"       TEXT,
ADD COLUMN "f9GMCApprovalDate"     TEXT,
ADD COLUMN "f9InitiatorContactNo"  TEXT,
ADD COLUMN "f9Remarks"             TEXT,
ADD COLUMN "f9ClusterDirectorId"   TEXT,
ADD COLUMN "f9GMCMemberId"         TEXT,
ADD COLUMN "f9FacilityManagerId"   TEXT,
ADD COLUMN "f9BoardResolutionNo"   TEXT,
ADD COLUMN "f9BoardResolutionDate" TEXT,
ADD COLUMN "f9StampDutyOpinionNo"  TEXT,
ADD COLUMN "f9StampDutyRs"         TEXT,
ADD COLUMN "f9LegalFeeRs"          TEXT,
ADD COLUMN "f9ReferenceNo"         TEXT,
ADD COLUMN "f9DeedNo"              TEXT,
ADD COLUMN "f9DeedDate"            TEXT,
ADD COLUMN "f9LandRegistryRegNo"   TEXT,
ADD COLUMN "f9DateHandoverFinance" TEXT,
ADD COLUMN "f9OfficialRemarks"     TEXT,
ADD COLUMN "f9LegalReviewCompleted" BOOLEAN DEFAULT false;
